name: Snacktime's Resume/CV
description:
meta_description: "Snacktime's Resume/CV"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "http://127.0.0.1:4000/"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config

comment:
  provider: "disqus"
  disqus:
    shortname: "introduce81"
